import type { WorldData } from '../types/map';

export const DEFAULT_WORLD: WorldData = {
  scenes: {
    outer_square: {
      id: 'outer_square',
      name: '青云峰·外门广场',
      description:
        '这里是青云峰的外门广场，云雾缭绕，几名外门弟子正在此处切磋。空气中弥漫着淡淡的灵气。',
      safe_zone: true,
      environment: 'mountain',
      level_range: [1, 5],
      exits: {
        east: 'mountain_path',
        north: 'herb_garden',
      },
      entities: [
        { template_id: 'npc_jiandong', type: 'npc', visible: true },
        { template_id: 'item_lingshi_fragment', type: 'item', quantity: 3, visible: true },
        { template_id: 'item_huiqi_dan', type: 'item', quantity: 1, visible: true },
      ],
    },
    mountain_path: {
      id: 'mountain_path',
      name: '内门山道',
      description: '通往内门的崎岖山道，两旁古木参天，偶尔能听到灵兽的啼鸣。',
      safe_zone: false,
      environment: 'mountain',
      level_range: [3, 8],
      exits: {
        west: 'outer_square',
      },
      entities: [],
    },
    herb_garden: {
      id: 'herb_garden',
      name: '灵药圃',
      description:
        '这里种植着各种珍稀灵药，药香扑鼻。一名老者正弯腰打理着药草。',
      safe_zone: true,
      environment: 'forest',
      level_range: [1, 10],
      exits: {
        south: 'outer_square',
      },
      entities: [
        { template_id: 'npc_yaoyuan_elder', type: 'npc', visible: true },
      ],
    },
  },
  npcs: {
    npc_jiandong: {
      id: 'npc_jiandong',
      name: '剑童',
      type: 'npc',
      description: '一个背着木剑的小童，眼神清澈。',
      tags: ['可交互'],
      visible: true,
      level: 1,
      realm: '炼气期',
      hp: 50,
      max_hp: 50,
      mp: 10,
      max_mp: 10,
      attack: 4,
      defense: 2,
      speed: 8,
      ai: 'passive',
      dialogue: '小道友，你也是来修炼的吗？',
      drop: [],
    },
    npc_yaoyuan_elder: {
      id: 'npc_yaoyuan_elder',
      name: '药园长老',
      type: 'npc',
      description: '面容慈祥的老者，身上带着浓郁的药香。',
      tags: ['可交互', '商人'],
      visible: true,
      level: 30,
      realm: '金丹期',
      hp: 5000,
      max_hp: 5000,
      mp: 2000,
      max_mp: 2000,
      attack: 80,
      defense: 60,
      speed: 12,
      ai: 'passive',
      dialogue: '这片灵药圃的每一株草木，都凝聚了老夫数十年的心血。',
      drop: [],
    },
  },
  items: {
    item_lingshi_fragment: {
      id: 'item_lingshi_fragment',
      name: '灵石碎片',
      type: 'item',
      description: '散发着微弱光芒的灵石碎片，可用于修炼或交易。',
      tags: ['材料', '货币'],
      visible: true,
      rarity: 'common',
      stackable: true,
      max_stack: 999,
      value: 5,
      weight: 0.1,
      usable: false,
    },
    item_huiqi_dan: {
      id: 'item_huiqi_dan',
      name: '回气丹',
      type: 'item',
      description: '一颗散发着药香的丹药，服用后可恢复一定量的法力。',
      tags: ['丹药', '消耗品'],
      visible: true,
      rarity: 'uncommon',
      stackable: true,
      max_stack: 20,
      value: 30,
      weight: 0.05,
      usable: true,
      effect: { type: 'restore_mp', value: 20 },
    },
  },
};
